//! core/src/ota.rs — over-the-air blocklist update *policy* (plan item 3.5):
//! the manifest schema, the baked update-signing public keys, and the pure
//! acceptance rules every consumer applies identically — version monotonicity
//! (no rollback) and wholesale rejection of any update that would block a
//! whitelisted domain.
//!
//! Deliberately NO networking and NO signature-verification crypto in here:
//! this crate stays dependency-light (plan Part H — the mobile/UniFFI
//! surface). The app's `src-tauri/src/ota.rs` does HTTP (`ureq`) and Ed25519
//! verification (`ed25519-dalek`); the extension's `bg/ota.js` does the same
//! with `fetch` and the vendored `@noble/ed25519`. Both enforce the SAME
//! rules implemented here; the JS twin re-implements them (pinned against
//! each other by `extension/tests/test-ota.cjs` and this module's `#[test]`s).
//!
//! ## The scheme (one signature, two verifiers)
//! The publisher (CI, `.github/workflows/release-lists.yml` via
//! `scripts/ota/sign-manifest.mjs`) sha256-hashes every list file, writes
//! `lists-manifest.json`, and signs the manifest's **raw file bytes** with
//! plain Ed25519 (RFC 8032, no prehash) — NOT minisign: minisign signs a
//! Blake2b-512 prehash, which the vendored single-file `@noble/ed25519` the
//! extension uses cannot verify. The signature ships next to the manifest as
//! `lists-manifest.json.sig`, whose entire content is the 64-byte signature
//! **hex-encoded** (128 lowercase hex chars, optional trailing whitespace).
//! Each list file is then integrity-checked against its sha256 from the
//! (signed) manifest, so only the manifest itself needs a signature.
//!
//! ## Manifest shape
//! ```json
//! {
//!   "version": 3,
//!   "created": "2026-07-12T00:00:00Z",
//!   "files": {
//!     "domains_part1.json": { "sha256": "<64 hex>", "size": 4194304 },
//!     "keywords.json":      { "sha256": "<64 hex>", "size": 20480 }
//!   }
//! }
//! ```
//! Keys of `files` are release-asset **basenames** (GitHub release assets are
//! flat). A name starting with `domains` is a domain-list file
//! (`{"domains": [...]}`); the name `keywords.json` is the keyword file
//! (`{"keywords": [...]}`) — so a future `domains_part4.json` needs no client
//! update. `version` is a monotonically increasing integer (see
//! `release-lists.yml` for how CI derives it from the release tag).

use serde::Deserialize;
use std::collections::{BTreeMap, HashSet};

/// Update-signing public keys (raw 32-byte Ed25519, hex), checked in order.
/// TWO keys so a compromise/loss of the active key is rotatable without
/// stranding deployed clients (plan 3.5's "main risk" mitigation): rotate by
/// promoting the spare in a signed release, then baking a fresh spare.
///
/// These are the DEV keys — generated by `scripts/ota/sign-manifest.mjs
/// --gen-key` for pre-release testing. The corresponding private keys exist
/// ONLY as the `OTA_SIGNING_KEY` GitHub Actions secret (+ the owner's offline
/// backup) — never in this repository. See docs/OTA_KEYS.md for the rotation
/// procedure and what to do before the first real release.
pub const OTA_PUBKEY_ACTIVE_HEX: &str =
    "839a62f44c288c4f339349b0630bf8c870efe5cd6701a3ea31056655d8a6de45";
pub const OTA_PUBKEY_SPARE_HEX: &str =
    "a49202aca120c91a330ca5a803a9ef8b39462d3efea9aa68b011cd1fc1d25a26";

/// Both baked keys, active first — verifiers accept a signature from either.
pub const OTA_PUBKEYS_HEX: [&str; 2] = [OTA_PUBKEY_ACTIVE_HEX, OTA_PUBKEY_SPARE_HEX];

/// Hard cap on the summed `size` of every file in a manifest (and on actual
/// downloaded bytes). An update bigger than this is rejected wholesale — the
/// full bundled lists are ~10.5MB today, so 40MB is generous headroom without
/// letting a compromised/hijacked release asset fill the disk.
pub const OTA_MAX_TOTAL_BYTES: u64 = 40 * 1024 * 1024;

/// Cap on the manifest file itself (it's a few KB of JSON).
pub const OTA_MAX_MANIFEST_BYTES: u64 = 1024 * 1024;

/// Cap on the `.sig` file (128 hex chars + whitespace).
pub const OTA_MAX_SIG_BYTES: u64 = 4096;

/// One entry in `OtaManifest::files`.
#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
pub struct OtaFileEntry {
    /// Lowercase hex sha256 of the file's raw bytes.
    pub sha256: String,
    /// Exact byte size — checked against the download before hashing.
    pub size: u64,
}

/// The signed manifest. `files` is a `BTreeMap` so iteration order is stable
/// (useful for logs/tests); the signature covers the raw bytes, so key order
/// in the JSON itself is irrelevant to verification.
#[derive(Debug, Clone, Deserialize)]
pub struct OtaManifest {
    pub version: u64,
    #[serde(default)]
    pub created: String,
    pub files: BTreeMap<String, OtaFileEntry>,
}

/// Parse + structurally validate a manifest. Rejects:
/// - unparseable JSON / missing fields,
/// - `version == 0` (versions start at 1 so "nothing installed" is
///   representable as 0 everywhere),
/// - an empty `files` map,
/// - any file name that isn't a plain `[a-z0-9_.-]` basename ending in
///   `.json` (no path separators — these names are written to disk),
/// - any file name that isn't a known list kind (`domains*` / `keywords.json`),
/// - a malformed `sha256` (must be exactly 64 lowercase hex chars),
/// - summed sizes over [`OTA_MAX_TOTAL_BYTES`].
pub fn parse_manifest(bytes: &[u8]) -> Result<OtaManifest, String> {
    let m: OtaManifest =
        serde_json::from_slice(bytes).map_err(|e| format!("manifest JSON invalid: {e}"))?;
    if m.version == 0 {
        return Err("manifest version must be >= 1".into());
    }
    if m.files.is_empty() {
        return Err("manifest lists no files".into());
    }
    let mut total: u64 = 0;
    for (name, entry) in &m.files {
        if !is_safe_asset_name(name) {
            return Err(format!("unsafe asset name in manifest: {name:?}"));
        }
        if !is_known_list_kind(name) {
            return Err(format!("unknown list kind in manifest: {name:?}"));
        }
        if entry.sha256.len() != 64
            || !entry
                .sha256
                .bytes()
                .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
        {
            return Err(format!("malformed sha256 for {name:?}"));
        }
        total = total
            .checked_add(entry.size)
            .ok_or_else(|| "manifest sizes overflow".to_string())?;
    }
    if total > OTA_MAX_TOTAL_BYTES {
        return Err(format!(
            "manifest total size {total} exceeds the {OTA_MAX_TOTAL_BYTES}-byte cap"
        ));
    }
    Ok(m)
}

/// A plain basename: no path separators, no dot-dot, ASCII `[a-z0-9_.-]`
/// only, ends with `.json`. These strings become file names under
/// `<app_data_dir>/lists/`, so this is a write-path safety check, not just
/// tidiness.
pub fn is_safe_asset_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 64
        && name.ends_with(".json")
        && !name.contains("..")
        && name.bytes().all(|b| {
            b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_' || b == b'-' || b == b'.'
        })
}

/// Is this manifest entry a list file this client knows how to consume?
/// `domains*.json` → a `{"domains": [...]}` file; `keywords.json` → the
/// `{"keywords": [...]}` file.
pub fn is_known_list_kind(name: &str) -> bool {
    name == "keywords.json" || (name.starts_with("domains") && name.ends_with(".json"))
}

/// Version monotonicity — the anti-rollback rule. `installed == 0` means
/// "nothing installed yet" (built-ins only), so any `new_version >= 1`
/// qualifies; otherwise strictly greater. Equal versions are NOT re-applied
/// (a same-version manifest with different bytes would be a signing mistake
/// or an attack — either way, refuse).
pub fn version_is_acceptable(new_version: u64, installed: u64) -> bool {
    new_version > installed
}

/// The whitelist safety floor: reject an update wholesale if any of its
/// domains would block a domain on `matching::WHITELIST_DOMAINS` — exact
/// match OR by the parent walk (`lists::is_domain_listed`), i.e. a blocklist
/// entry `github.com` (or a hypothetical parent like `com`) blocks
/// `github.com`, so both are collisions. Returns the first colliding
/// whitelist domain for the error message, or `None` if the set is clean.
///
/// `domains` must already be normalized/lowercase (list files are; the
/// consumers reject non-lowercase entries before calling this).
pub fn whitelist_collision(domains: &HashSet<String>) -> Option<&'static str> {
    crate::matching::WHITELIST_DOMAINS
        .iter()
        .copied()
        .find(|&w| crate::lists::is_domain_listed(w, domains))
}

/// Decode a hex string (even length, lowercase or uppercase) into bytes.
/// Tolerates surrounding ASCII whitespace (the `.sig` file may end in a
/// newline). Errors on odd length or any non-hex character.
pub fn decode_hex(s: &str) -> Result<Vec<u8>, String> {
    let s = s.trim();
    if s.len() % 2 != 0 {
        return Err("hex string has odd length".into());
    }
    let mut out = Vec::with_capacity(s.len() / 2);
    let bytes = s.as_bytes();
    for pair in bytes.chunks_exact(2) {
        let hi =
            hex_val(pair[0]).ok_or_else(|| format!("invalid hex byte {:?}", pair[0] as char))?;
        let lo =
            hex_val(pair[1]).ok_or_else(|| format!("invalid hex byte {:?}", pair[1] as char))?;
        out.push((hi << 4) | lo);
    }
    Ok(out)
}

fn hex_val(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

/// Encode bytes as lowercase hex (the inverse of [`decode_hex`]; used for
/// sha256 comparison against manifest entries).
pub fn encode_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut s = String::with_capacity(bytes.len() * 2);
    for &b in bytes {
        s.push(HEX[(b >> 4) as usize] as char);
        s.push(HEX[(b & 0x0f) as usize] as char);
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_manifest_json(version: u64) -> String {
        format!(
            r#"{{
              "version": {version},
              "created": "2026-07-12T00:00:00Z",
              "files": {{
                "domains_part1.json": {{ "sha256": "{h}", "size": 100 }},
                "keywords.json":      {{ "sha256": "{h}", "size": 50 }}
              }}
            }}"#,
            h = "a".repeat(64)
        )
    }

    #[test]
    fn parse_manifest_accepts_wellformed() {
        let m = parse_manifest(sample_manifest_json(3).as_bytes()).expect("must parse");
        assert_eq!(m.version, 3);
        assert_eq!(m.files.len(), 2);
        assert_eq!(m.files["keywords.json"].size, 50);
    }

    #[test]
    fn parse_manifest_rejects_version_zero_and_empty_files() {
        assert!(parse_manifest(sample_manifest_json(0).as_bytes()).is_err());
        let empty = r#"{"version": 1, "files": {}}"#;
        assert!(parse_manifest(empty.as_bytes()).is_err());
    }

    #[test]
    fn parse_manifest_rejects_unsafe_and_unknown_names() {
        let h = "b".repeat(64);
        for bad in [
            "../evil.json",       // traversal
            "domains/part1.json", // path separator
            "DOMAINS_PART1.JSON", // uppercase
            "domains_part1.exe",  // not .json
            "mystery.json",       // not a known list kind
        ] {
            let j = format!(r#"{{"version":1,"files":{{"{bad}":{{"sha256":"{h}","size":1}}}}}}"#);
            assert!(parse_manifest(j.as_bytes()).is_err(), "must reject {bad:?}");
        }
    }

    #[test]
    fn parse_manifest_rejects_malformed_sha256_and_oversize() {
        let j = format!(
            r#"{{"version":1,"files":{{"domains_part1.json":{{"sha256":"{}","size":1}}}}}}"#,
            "Z".repeat(64)
        );
        assert!(parse_manifest(j.as_bytes()).is_err(), "non-hex sha256");
        let j = format!(
            r#"{{"version":1,"files":{{"domains_part1.json":{{"sha256":"{}","size":{}}}}}}}"#,
            "a".repeat(64),
            OTA_MAX_TOTAL_BYTES + 1
        );
        assert!(
            parse_manifest(j.as_bytes()).is_err(),
            "over the total-size cap"
        );
    }

    #[test]
    fn version_monotonicity() {
        assert!(version_is_acceptable(1, 0)); // first install
        assert!(version_is_acceptable(7, 3)); // upgrade
        assert!(!version_is_acceptable(3, 3)); // same version — refuse
        assert!(!version_is_acceptable(2, 3)); // rollback — refuse
        assert!(!version_is_acceptable(0, 0)); // nonsense — refuse
    }

    #[test]
    fn whitelist_collision_exact_and_parent() {
        let clean: std::collections::HashSet<String> =
            ["example-adult-site.com".to_string()].into_iter().collect();
        assert_eq!(whitelist_collision(&clean), None);

        // Exact: blocklist entry IS a whitelisted domain.
        let exact: std::collections::HashSet<String> =
            ["github.com".to_string()].into_iter().collect();
        assert_eq!(whitelist_collision(&exact), Some("github.com"));

        // Parent walk: whitelisted `docs.google.com` would be blocked by a
        // blocklist entry `google.com` (its parent).
        let parent: std::collections::HashSet<String> =
            ["google.com".to_string()].into_iter().collect();
        assert!(whitelist_collision(&parent).is_some());
    }

    #[test]
    fn hex_roundtrip_and_errors() {
        assert_eq!(decode_hex("00ffA5").unwrap(), vec![0x00, 0xff, 0xa5]);
        assert_eq!(decode_hex("  0a0b\n").unwrap(), vec![0x0a, 0x0b]); // tolerated whitespace
        assert!(decode_hex("abc").is_err()); // odd length
        assert!(decode_hex("zz").is_err()); // non-hex
        assert_eq!(encode_hex(&[0x00, 0xff, 0xa5]), "00ffa5");
        let pk = decode_hex(OTA_PUBKEY_ACTIVE_HEX).unwrap();
        assert_eq!(pk.len(), 32, "baked active pubkey must be 32 bytes");
        let pk = decode_hex(OTA_PUBKEY_SPARE_HEX).unwrap();
        assert_eq!(pk.len(), 32, "baked spare pubkey must be 32 bytes");
    }

    #[test]
    fn safe_asset_names() {
        assert!(is_safe_asset_name("domains_part1.json"));
        assert!(is_safe_asset_name("domains_ai.json"));
        assert!(is_safe_asset_name("keywords.json"));
        assert!(!is_safe_asset_name("..\\evil.json"));
        assert!(!is_safe_asset_name("a/b.json"));
        assert!(!is_safe_asset_name(""));
        assert!(!is_safe_asset_name("noext"));
    }
}
